// <auto-generated />
using KullaniciListe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KullaniciListe.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KullaniciListe.Data.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciMail")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciNumara")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciPozisyon")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciSoyadi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciYas")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
